-- AlterTable
ALTER TABLE "SponsorLead" ADD COLUMN "sourceUrl" TEXT,
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "SponsorLead" ALTER COLUMN "updatedAt" DROP DEFAULT;
