-- AlterTable
ALTER TABLE "DiscoveryRun" ADD COLUMN "streamsFound" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "streamsMatched" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "vodsFetched" INTEGER NOT NULL DEFAULT 0;
